name: Build
on:
  push:
jobs:
  code_check:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.6
    steps:
      - uses: actions/checkout@v1
      - name: Cache modules
        uses: actions/cache@v2
        id: node_cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.node_cache.outputs.cache-hit != 'true' }}
        run: npm i
      - name: Execute code check
        run: npm run validate
